ips:
  - ip: 192.168.20.133
    user: aaron
    password: "    "
    port: 22
    role: fp
  - ip: 192.168.20.133
    user: aaron
    password: "    "
    port: 22
    role: ops

port:
  default:
    prometheus: 9090
    grafana: 3000
    pushgateway: 9091
  ops:
    prometheus: 32190
    grafana: 32123
    pushgateway: 32191

log:
  level: "debug"
  file: "ops_cli.log"